In [10]:
maps = {
    "customer": {
        "C001": 1,
        "C002": 2,
        "C003": 3,
        "C004": 4
    },
    # "payment": {
    #     "credit_card": 1,
    #     "boleto": 2,
    #     "voucher": 3,
    #     "not_defined": 5   # default key
    # }
}

In [11]:
import pandas as pd

df = pd.DataFrame({
    "customer_id": [
        "C001", "C002", "C003", "C004",
        "C005", "C001", "C999", "C002",
        "C003", "C888"
    ],
    # "payment_type": [
    #     "credit_card", "boleto", "voucher", "credit_card",
    #     "unknown", "boleto", "credit_card", "crypto",
    #     "voucher", None
    # ]
})

df

  customer_id
0        C001
1        C002
2        C003
3        C004
4        C005
5        C001
6        C999
7        C002
8        C003
9        C888

In [12]:
df["customer_key"] = df["customer_id"].map(maps["customer"])

In [ ]:
# df["payment_type_key"] = (
#     df["payment_type"]
#     .map(maps["payment"])
#     .fillna(maps["payment"].get("not_defined", 5))
#     .astype(int)
# )

In [13]:
df

  customer_id  customer_key
0        C001           1.0
1        C002           2.0
2        C003           3.0
3        C004           4.0
4        C005           NaN
5        C001           1.0
6        C999           NaN
7        C002           2.0
8        C003           3.0
9        C888           NaN